# Generated by Django 5.0.6 on 2024-07-16 17:23

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='Russia', max_length=2, verbose_name='Страна'),
        ),
    ]
