# Generated by Django 5.0.6 on 2024-07-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.CharField(default='', max_length=150, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(default='@', max_length=150, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(default='https://', max_length=150, verbose_name='Сайт'),
        ),
    ]
