# Generated by Django 5.0.6 on 2024-07-28 18:04

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_github_user_telegram_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='RU', max_length=2, verbose_name='Страна'),
        ),
    ]
