# Generated by Django 5.0.6 on 2024-06-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0004_remove_message_sent_at_mailings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mailings',
            new_name='Mailing',
        ),
    ]
