# Generated by Django 5.0.6 on 2024-06-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0005_rename_mailings_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='first_send',
            field=models.DateField(auto_now_add=True, verbose_name='Дата и время отправки'),
        ),
    ]
