# Generated by Django 5.0.6 on 2024-06-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0006_alter_mailing_first_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='first_send',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки'),
        ),
    ]
