# Generated by Django 5.0.6 on 2024-06-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0007_alter_mailing_first_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='clients',
        ),
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(related_name='mailings', to='mailing_service.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='finish_send',
            field=models.DateTimeField(default='2025-01-01 00:00', verbose_name='Дата и время завершения рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
