# Generated by Django 5.0.6 on 2024-06-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0008_remove_mailing_clients_mailing_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_send',
            field=models.DateTimeField(default='2025-01-01 00:00:00', verbose_name='Дата и время завершения рассылки'),
        ),
    ]
