# Generated by Django 5.0.6 on 2024-06-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0010_mailinglogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_send',
            field=models.DateTimeField(auto_created=True, default='2025-01-01 00:00:00', verbose_name='Дата и время завершения рассылки'),
        ),
    ]
