# Generated by Django 5.0.6 on 2024-06-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0011_alter_mailing_finish_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='mailing_service.client', verbose_name='Клиент'),
        ),
    ]
