# Generated by Django 5.0.6 on 2024-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0012_alter_mailing_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, related_name='mailings', to='mailing_service.client', verbose_name='Клиент'),
        ),
    ]
