# Generated by Django 5.0.6 on 2024-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0013_alter_mailing_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='first_send',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата и время отправки'),
        ),
    ]
