# Generated by Django 5.0.6 on 2024-06-22 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0014_alter_mailing_first_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='first_send',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 6, 22, 19, 15, 44, 413643), verbose_name='Дата и время отправки'),
        ),
    ]
