# Generated by Django 5.0.6 on 2024-06-22 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0015_alter_mailing_first_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_send',
            field=models.DateTimeField(default='2025-01-01 00:00:00', verbose_name='Дата и время завершения рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_send',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 19, 36, 59, 744608), verbose_name='Дата и время отправки'),
        ),
    ]
