# Generated by Django 5.0.6 on 2024-06-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0022_alter_mailing_finish_send_alter_mailing_first_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(related_name='mailings', to='mailing_service.client', verbose_name='Клиент'),
        ),
    ]
