# Generated by Django 5.0.6 on 2024-07-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0027_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='added_at',
            field=models.DateField(auto_now=True, verbose_name='Дата добавления'),
        ),
    ]
