# Generated by Django 5.0.6 on 2024-07-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0028_client_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='added_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
